// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYro7J080RZ5FNQGaLNLYguJRTPcmQ8g',
    appId: '1:279881843781:web:232b8c8a1669a6152ecf2c',
    messagingSenderId: '279881843781',
    projectId: 'my-todo-mission-app',
    authDomain: 'my-todo-mission-app.firebaseapp.com',
    storageBucket: 'my-todo-mission-app.firebasestorage.app',
    measurementId: 'G-H2B9G6FCB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFjw99feoBbhBOqzGtZfSgd2WeoxnxB0',
    appId: '1:279881843781:android:e183ae2aa7f67eb52ecf2c',
    messagingSenderId: '279881843781',
    projectId: 'my-todo-mission-app',
    storageBucket: 'my-todo-mission-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDyXVr8FMzz3sVBj2JKK5Uhk0iTqkrNJw',
    appId: '1:279881843781:ios:005c3236b2131f3f2ecf2c',
    messagingSenderId: '279881843781',
    projectId: 'my-todo-mission-app',
    storageBucket: 'my-todo-mission-app.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDyXVr8FMzz3sVBj2JKK5Uhk0iTqkrNJw',
    appId: '1:279881843781:ios:005c3236b2131f3f2ecf2c',
    messagingSenderId: '279881843781',
    projectId: 'my-todo-mission-app',
    storageBucket: 'my-todo-mission-app.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIYro7J080RZ5FNQGaLNLYguJRTPcmQ8g',
    appId: '1:279881843781:web:8be50442bd14f81c2ecf2c',
    messagingSenderId: '279881843781',
    projectId: 'my-todo-mission-app',
    authDomain: 'my-todo-mission-app.firebaseapp.com',
    storageBucket: 'my-todo-mission-app.firebasestorage.app',
    measurementId: 'G-74NNZ518GK',
  );
}
